// Screen names
export const HOME_SCREEN = 'HOME_SCREEN';
export const SIGNUP_SCREEN = 'SIGNUP_SCREEN';
export const DASHBOARD_SCREEN = 'DASHBOARD_SCREEN';
export const FORGOT_PASSWORD_SCREEN = 'FORGOT_PASSWORD';
export const SYSTEM_SCREEN = 'SYSTEM_SCREEN';
export const SEARCH_SCREEN = 'SEARCH_SCREEN';
export const MORE_SCREEN = 'MORE_SCREEN';
export const ABOUT_SCREEN = 'ABOUT_SCREEN';
export const GOVERNANCE_SCREEN = 'GOVERNANCE_SCREEN';
export const CONTACT_SCREEN = 'CONTACT_SCREEN';
export const RESOURCES_SCREEN = 'RESOURCES_SCREEN';
export const ACCOUNT_SCREEN = 'ACCOUNT_SCREEN';
export const RESULTS_SCREEN = 'RESUKTS_SCREEN';
