// Screen names
export const HOME_SCREEN = 'HOME_SCREEN';
export const SIGNUP_SCREEN = 'SIGNUP_SCREEN';
export const DASHBOARD_SCREEN = 'DASHBOARD_SCREEN';
export const FORGOT_PASSWORD_SCREEN = 'FORGOT_PASSWORD';