// Screen names
export const HOME_SCREEN = 'HOME_SCREEN';
export const SIGNUP_SCREEN = 'SIGNUP_SCREEN';
export const DASHBOARD_SCREEN = 'DASHBOARD_SCREEN';
export const FORGOT_PASSWORD_SCREEN = 'FORGOT_PASSWORD';
export const SYSTEM_SCREEN = 'SYSTEM_SCREEN';
export const SEARCH_SCREEN = 'SEARCH_SCREEN';
export const MORE_SCREEN = 'MORE_SCREEN';
