// Module constants
export const DASHBOARD_SAGA = 'DASHBOARD_SAGA';
export const DASHBOARD_REDUCER = 'DASHBOARD_REDUCER';
export const DASHBOARD_PREFIX = 'DASHBOARD';

// Action types
export const GET_NOTIFICATIONS = `${DASHBOARD_PREFIX}/GET_NOTIFICATIONS`;
export const SET_NOTIFICATIONS = `${DASHBOARD_PREFIX}/SET_NOTIFICATIONS`;

// State
export const NOTIFICATIONS = 'NOTIFICATIONS';
